export default [{
    name:'首页',
    key:'0',
    path:'/admin/home'
},
{
    name:'商品管理',
    key:'1',
    path:'/admin/food',
    children:[
        {
            name:'商品列表',
            path:'/admin/food/list',
            key:'1-0',
            children:[
                {
                    name:'商品分类列表',
                    path:'/admin/food/list/type',
                    key:'1-0-0'
                }
            ]
        },
        {
            name:'商品添加',
            path:'/admin/food/add',
            key:'1-1',
        },
        {
            name:'上传file',
            path:'/admin/food/file',
            key:'1-2',
        },
        {
            name:'上传base64',
            path:'/admin/food/base64',
            key:'1-3',
        },
        {
            name:'上传antd',
            path:'/admin/food/antd',
            key:'1-4',
        }
    ]
},
{
    name:'数据统计',
    key:'2',
    path:'/admin/echarts',
    children:[
        {
            name:'饼型统计',
            key:'2-0',
            path:'/admin/echarts/pie'
        },
        {
            name:'折线统计',
            key:'2-1',
            path:'/admin/echarts/line'
        }
    ]
}
]